version: '3.4'

services:
  inventoryapp:
    image: ${DOCKER_REGISTRY-}inventoryapp
    build:
      context: .
      dockerfile: ./Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ../APIGateway/Dockerfile


  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: ../AuthenticationAPI/Dockerfile

